name: PupusasInventory

on:
  push:
    branches:
        - main 

jobs:
  DeployingPipeline:
    runs-on: self-hosted

    steps:
      - uses: actions/checkout@v4

      - name: Connect to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
#ADD THE CONFIG
