name: PupusasInventory

on:
  push:
    branches:
        - main 

jobs:
  DeployingPipeline:
    runs-on: self-hosted

    steps:
      - uses: actions/checkout@v4

      - name: Connect to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: "Build Image and Push to Docker HUB"
        run: |
          docker build -t luris26/inventory-final:$GITHUB_RUN_ID .
          docker push luris26/inventory-final:$GITHUB_RUN_ID

          - name: Build Kubernetes
          run: |
            for file in ./kubeInventory/*; do
                echo "envsubst applying to $file"
                cat $file | envsubst | kubectl apply -f -
            done
#ADD THE CONFIG and see if runns

